### ISSUE TITLE
The pretrained-model download link is not alivable

### ISSUE THREAD

**Issue by fanhongxing** [d-li14/efficientnet-lite.pytorch#1]
Hi,the pretrained-model download link is not alivabel, could you please update it? And what should i set the mean and std?

**Comment by d-li14** [comment]
Training is still in progress. Please stay tuned. I will notify you as soon as they are released.

**Comment by fanhongxing** [comment]
Thanks a lot!

**Comment by vilon888** [comment]
> Training is still in progress. Please stay tuned. I will notify you as soon as they are released.

Hi, are these pretraied-models available?
